#!/usr/bin/env bash
# Encodes the synthesised WAV stems (public/film-rd/audio/*.wav, regenerated by
# `python3 film/audio/synth.py`, not tracked) to the Opus files the edit plays
# (public/film-rd/audio/*.ogg, tracked). Remotion decodes them with its ffmpeg
# and the Studio plays them natively.
set -e
cd "$(dirname "$0")/.."
for w in public/film-rd/audio/*.wav; do
  o="${w%.wav}.ogg"
  npx remotion ffmpeg -y -loglevel error -i "$w" -c:a libopus -b:a 128k -vbr on -application audio "$o"
  echo "$(basename "$w") → $(du -k "$o" | cut -f1) kB"
done
